### PR TITLE
Added Codeowners

### PR DESCRIPTION
**Pull request by LukasLJL**
# Skiosa - PR
- [x] documentation can't be split up into smaller logical units

### CODE REVIEW

**Comment by grossamos** [comment]
Makes sense when looking at it from an organisational perspective. 

Would however still pose the question if it should rather be @jeppard and @grossamos (when taking recent stories and changes into account)

**Comment by jeppard** [comment]
In my opinion i would take Code ownership for the Template and po and scrum Master take Code ownership of content/* and ads/appendix.tex.

I would be responisible for Template chsnges and PO or Srum Lead for content

**Comment by LukasLJL** [comment]
We can´t negate Rule: https://docs.github.com/en/github-ae@latest/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners 
Is the current fix ok for everyone?

**Review by jeppard — APPROVED** [review]
lgtm

**Review by grossamos — APPROVED** [review]

**Pull request merged**
